### ISSUE TITLE
Cannot Build with VS2015

### ISSUE THREAD

**Issue by codingkiller** [yigityuce/HidApi#1]
Including path:C:\Program Files (x86)\Windows Kits\8.1\Include\shared;
still cannot build it.

**Comment by yigityuce** [comment]
"-lsetupapi" linker flag must be added to linker librariers. It is mentioned in the readme file's dependencies part.

[https://github.com/yigityuce/HidApi#dependencies](https://github.com/yigityuce/HidApi#dependencies)
